### ISSUE TITLE
训练时出错

### ISSUE THREAD

**Issue by neverland0621** [PaddlePaddle/models#1260]
我用单张卡训练报错如下：
```
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    train(args, config, train_file_list, optimizer_method="momentum")
  File "train.py", line 92, in train
    exe.run(fluid.default_startup_program())
  File "/home/jw/.conda/envs/Paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: Enforce failed. Expected allocating <= available, but received allocating:10243394109 > available:426114816.
Insufficient GPU memory to allocation. at [/paddle/paddle/fluid/platform/gpu_info.cc:120]
```

应该是内存不足的问题，所以我换成了3张卡，结果还是报错：

```
Traceback (most recent call last):
  File "train.py", line 183, in <module>
    train(args, config, train_file_list, optimizer_method="momentum")
  File "train.py", line 92, in train
    exe.run(fluid.default_startup_program())
  File "/home/jw/.conda/envs/Paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 470, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: no CUDA-capable device is detected at [/paddle/paddle/fluid/platform/gpu_info.cc:33]
```
麻烦解答，谢谢。

**Comment by qingqing01** [comment]
1. PyramidBox模型，使用P40, 24G显存，单卡batch size最大是5。如果您使用的GPU显存较小，需要减少batch size。
2. 可以贴下`nvidia-smi`的信息吗？

**Comment by neverland0621** [comment]
好的，谢谢。
我刚才试了batch_size设置成1，结果还是显存不足的问题。第二个no CUDA-capable device是我参数没设置好已经解决了，现在存在的就是显存不够的问题。
我的显卡信息，3张1080 ti，信息如下：
```
 NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:03:00.0 Off |                  N/A |
| 31%   51C    P2    57W / 250W |  10331MiB / 11178MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:04:00.0  On |                  N/A |
| 29%   47C    P8    19W / 250W |  10405MiB / 11177MiB |     25%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:84:00.0 Off |                  N/A |
| 21%   39C    P8     9W / 250W |  10141MiB / 11178MiB |      0%      Default
```

**Comment by qingqing01** [comment]
@neverland0621 可以参考 https://github.com/PaddlePaddle/models/issues/1262#issuecomment-422724707

抱歉，我们训练都是P40 24G显存，之前没跑过显存较小的机器，稍后我们测下。
