### ISSUE TITLE
GPU一直显示各种内存溢出

### ISSUE THREAD

**Issue by shanzhengliu** [PaddlePaddle/models#4173]
代码是cycleGan的内容，报错内容是
Out of memory error on GPU 0. Cannot allocate 80.000244MB memory on GPU 0, available memory is only 76.089062MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please try one of the following suggestions:
   1) Decrease the batch size of your model.
   2) FLAGS_fraction_of_gpu_memory_to_use is 0.50 now, please set it to a higher value but less than 1.0.
      The command is `export FLAGS_fraction_of_gpu_memory_to_use=xxx`.

使用源码而且尝试了网上所说的 os.environ["FLAGS_fraction_of_gpu_memory_to_use"]="0.7"也无法解决，求助

**Comment by wanghaoshuang** [comment]
可以尝试设置这些FLAGS: https://www.paddlepaddle.org.cn/documentation/docs/zh/flags/memory_cn.html 同时建议升级到paddle1.6

**Comment by callmeivy** [comment]
您好，请问解决了吗？遇到同样的问题。

**Comment by shanzhengliu** [comment]
> 您好，请问解决了吗？遇到同样的问题。

搞定了，搜下网上其他的代码就好了，他自己的代码有bug，网上有其他实现的方法

**Comment by callmeivy** [comment]
> > 您好，请问解决了吗？遇到同样的问题。
> 
> 搞定了，搜下网上其他的代码就好了，他自己的代码有bug，网上有其他实现的方法

多谢回复，代码是kt-net，也怀疑有bug
